### ISSUE TITLE
Netlify won't build our site any more

### ISSUE THREAD

**Issue by craigbox** [istio/istio.io#16053]
as of ~18 hours ago all our Netlify deploys are failing. 

The errors are in one of the `babel --source-maps --minified --no-comments --presets minify` step of `gen_site.sh` but they don't seem consistent.

No changes to: node version, module version, any of the JS/TS files.

Some examples:

https://app.netlify.com/sites/preliminary-istio/deploys/67505e7ce5d55a00086ffb15

```
Error: /opt/build/repo/tmp/js/themes.js: Binding not found for ReferencedIdentifier "handleThemes" present in "CallExpression". Please report this at https://github.com/babel/minify/issues/new
2:53:49 AM:     at ReferencedIdentifier (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:199:19)
2:53:49 AM:     at newFn (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:205:17)
2:53:49 AM:     at bfsTraverse (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:38:43)
2:53:49 AM:     at Mangler.collect (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:235:7)
2:53:49 AM:     at Mangler.run (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:60:12)
2:53:49 AM:     at PluginPass.exit (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:546:19)
2:53:49 AM:     at newFn (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:170:14)
2:53:49 AM:     at NodePath._call (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:50:20)
2:53:49 AM:     at NodePath.call (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:18)
2:53:49 AM:     at NodePath.visit (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:8) {
2:53:49 AM:   code: 'BABEL_TRANSFORM_ERROR'
```

https://app.netlify.com/sites/preliminary-istio/deploys/67506620f384d9000852c9e7 (most common)
```
3:26:28 AM: TypeError: /opt/build/repo/tmp/js/kbdnav.js: Cannot read properties of undefined (reading 'get')
3:26:28 AM:     at ScopeTracker.addBinding (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:215:38)
3:26:28 AM:     at /opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:143:26
3:26:28 AM:     at Array.forEach (<anonymous>)
3:26:28 AM:     at Scopable (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:142:39)
3:26:28 AM:     at bfsTraverse (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:38:43)
3:26:28 AM:     at Mangler.collect (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:235:7)
3:26:28 AM:     at Mangler.run (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:60:12)
3:26:28 AM:     at PluginPass.exit (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:546:19)
3:26:28 AM:     at newFn (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:170:14)
3:26:28 AM:     at NodePath._call (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:50:20) {
3:26:28 AM:   code: 'BABEL_TRANSFORM_ERROR'
```

https://app.netlify.com/sites/preliminary-istio/deploys/6750d23c0a7bc6000872ffdc

```
11:07:34 AM: Error: /opt/build/repo/tmp/js/menu.js: Binding not found for ReferencedIdentifier "handleMenu" present in "CallExpression". Please report this at https://github.com/babel/minify/issues/new
11:07:34 AM:     at ReferencedIdentifier (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:199:19)
11:07:34 AM:     at newFn (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:205:17)
11:07:34 AM:     at bfsTraverse (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:38:43)
11:07:34 AM:     at Mangler.collect (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:235:7)
11:07:34 AM:     at Mangler.run (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:60:12)
11:07:34 AM:     at PluginPass.exit (/opt/build/repo/node_modules/babel-plugin-minify-mangle-names/lib/index.js:546:19)
11:07:34 AM:     at newFn (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/visitors.js:170:14)
11:07:34 AM:     at NodePath._call (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:50:20)
11:07:34 AM:     at NodePath.call (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:40:18)
11:07:34 AM:     at NodePath.visit (/opt/buildhome/.nvm/versions/node/v18.18.2/lib/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:97:8) {
11:07:34 AM:   code: 'BABEL_TRANSFORM_ERROR'
```

**Comment by craigbox** [comment]
It's looking like the problem is correlated with a new release of the `babel/traverse` module: https://www.npmjs.com/package/@babel/traverse

and smells like https://github.com/babel/babel/issues/16999.
